### ISSUE TITLE
Prevent selection of "Generated by..." text

### ISSUE THREAD

**Issue by dustinpaluch** [technomancy/scpaste#17]
It would be nice if the [scpaste-footer](https://github.com/technomancy/scpaste/blob/master/scpaste.el#L134) text were unselectable so a user can "select all + copy" and only get the intended contents of the paste.

``` 
-moz-user-select: none;  
-webkit-user-select: none;
-ms-user-select: none;
user-select: none;
```

**Comment by technomancy** [comment]
Good idea; thanks!
